# Docker for Mac Edge (as of 05/23/2020)
ARG DOCKER_FOR_MAC_KERNEL_IMAGE=docker/for-desktop-kernel:4.19.76-ce15f646db9b062dc947cfc0c1deab019fa63f96-amd64

FROM $DOCKER_FOR_MAC_KERNEL_IMAGE AS ksrc
FROM golang:1.13-alpine3.10

# install dev-tools
RUN apk add --no-cache neovim zsh git musl-dev curl

# install kubectl
RUN curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl \
&&  chmod +x /usr/bin/kubectl

# install go-tools
RUN go get -v golang.org/x/tools/gopls \
&&  go get -v sigs.k8s.io/controller-tools/cmd/controller-gen \
&&  go get -v github.com/golang/protobuf/protoc-gen-go

# copy kernel source code
COPY --from=ksrc /kernel-dev.tar /
COPY --from=ksrc /kernel.tar /
RUN cd / \
&&  tar xf kernel-dev.tar \
&&  tar xf kernel.tar \
&&  rm kernel**.tar

# Don't fail on wireguard install fail
RUN apk add --no-cache build-base perl wireguard-tools protobuf || true

COPY ./rootfs/bin/* /usr/bin/

ENTRYPOINT /usr/bin/setup-wireguard