version: "2.1"
services:
  registrar:
    build: ./registrar
    privileged: true
  fwupd:
    build: ./fwupd
    privileged: true
    pid: host
    environment:
    - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'