version: "2.1"
services:
  # Kubernetes and Wireguard initialization platform
  registrar:
    restart: 'on-failure'
    command: registrar
    build: ./registrar
    privileged: true
  
  # Wireguard module installer
  wireguard-installer:
    restart: no
    build: ./wireguard-balena
    privileged: true
  
  # Firmware updater
  fwupd:
    build: ./fwupd
    privileged: true
    restart: no
    pid: host
    environment:
    - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'